site_name: TestDaris

theme:
  name: material
  language: it
  custom_dir: Custom/overrides
  features:
    - announce.dismiss
    - navigation.instant
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false

extra_javascript:
  - 'docs/_Footer.md'
  - 'docs/_Sidebar.md'

plugins:
  - awesome-pages:
        collapse_single_pages: true
        strict: false
        order: asc
        sort_type: natural

markdown_extensions:
  - admonition
  - codehilite

nav:
    - ...
    - Ultima pagina: index.md
    - A boh Ultimissima pagina: Per-PA-e-Imprese.md
    - Link Title: https://lukasgeiter.com

docs_dir: docs
site_dir: site
