site_name: TestDaris

theme:
  name: readthedocs
  nav_style: dark

nav: custom_nav.yml

extra_javascript:
  - 'docs/_Footer.md'
  - 'docs/_Sidebar.md'

markdown_extensions:
  - admonition
  - codehilite

docs_dir: docs
site_dir: site
