site_name: TestDaris

theme:
  name: material
  language: it
  custom_dir: Custom/overrides
  features:
    - announce.dismiss

extra:
  generator: false

extra_javascript:
  - 'docs/_Footer.md'
  - 'docs/_Sidebar.md'

plugins:
  - include_dir_to_nav:
      file_name_as_title: true
      sort_file: true
      sort_directory: true
      recurse: true
      reverse_sort_directory: true

markdown_extensions:
  - admonition
  - codehilite

docs_dir: docs
site_dir: site
