site_name: TestDaris

nav:
  - Home: 'docs/Home.md'
  - Faq: 'docs/FAQ.md'
  - Docs:
    - 'docs/*'

theme:
  name: material

extra_javascript:
  - 'docs/_Footer.md'
  - 'docs/_Sidebar.md'

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite

docs_dir: docs
site_dir: site
