site_name: TestDaris

theme:
  name: readthedocs
  nav_style: dark

nav:
  - Home: 'Home'

extra_javascript:
  - 'docs/_Footer.md'
  - 'docs/_Sidebar.md'

plugins:
  - search
  - include_dir_to_nav

markdown_extensions:
  - admonition
  - codehilite

docs_dir: docs
site_dir: site
