site_name: TestDaris

nav:
  - Home: 'index.md'
  - Sidebar: '_Sidebar.md'
  - Footer: '_Footer.md'
  # Altri file o collegamenti della tua Wiki

theme:
  name: material

extra_javascript:
  - 'docs/_Footer.md'

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Home: 'Home.md'
  - Docs:
    - 'docs/*'

docs_dir: docs
site_dir: site
