site_name: TestDaris

nav:
  - Home: 'index.md'
  - Sidebar: '_Sidebar.md'
  - Footer: '_Footer.md'
  # Altri file o collegamenti della tua Wiki

theme:
  name: material

docs_dir: docs
site_dir: site