name: Deploy Wiki to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone Wiki repository
        run: |
          git clone https://github.com/DarisCappelletti/TestDaris.wiki.git ${{github.workspace}}/.wiki
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .wiki
          github_token: ${{ secrets.GH_TOKEN }}
