name: Pubblica Wiki su GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout della Wiki
      uses: actions/checkout@v2
      with:
        repository: DarisCappelletti/TestDaris.wiki
        path: wiki

    - name: Sposta i file della Wiki nella cartella docs
      run: mv wiki/* docs/

    - name: Pubblica su GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./docs
