name: Publish Wiki

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone wiki to root
      run: |
        git clone https://github.com/DarisCappelletti/TestDaris.wiki.git wiki_tmp
        cp -R ./wiki_tmp/* .
        rm -rf wiki_tmp

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update wiki files"
        git push

    - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install MkDocs
        run: npm install -g mkdocs

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          publish_dir: .  # Assicurati che corrisponda alla cartella di output di MkDocs
          publish_branch: master