name: Pubblica Wiki su GitHub Pages

on:
  push:
    branches:
      - main # Puoi modificare questo in base al tuo branch principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v2

    - name: Sposta i file della Wiki nella cartella docs
      run: mv path/to/wiki/* docs/

    - name: Pubblica su GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./docs
