name: Publish Wiki to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install -g markdown-to-gh-pages

      - name: Convert and Publish Wiki
        run: markdown-to-gh-pages --gh-repo TestDaris --gh-branch gh-pages --wiki-dir TestDaris.wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
