name: Pubblica Wiki su GitHub Pages

on:
  push:
    branches:
      - master # Puoi modificare questo in base al tuo branch principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v2

    - name: Configura ambiente di Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Installa le dipendenze
      run: npm install # o qualsiasi altro gestore di dipendenze che stai usando

    - name: Genera la Wiki in HTML (sostituisci con il tuo comando)
      run: npm run build-wiki # sostituisci con il comando necessario per generare la tua wiki

    - name: Sposta i file nella cartella docs
      run: |
        mkdir -p docs
        mv generated-wiki/* docs/

    - name: Pubblica su GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./docs
