name: Publish Wiki

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone wiki to root
      run: |
        git clone https://github.com/DarisCappelletti/TestDaris.wiki.git wiki_tmp
        cp -R ./wiki_tmp/* .
        rm -rf wiki_tmp

    - name: Install MkDocs
      run: npm install -g mkdocs

    - name: Install MkDocs Material theme
      run: pip install mkdocs-material

    - name: Build MkDocs
      run: mkdocs build

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update wiki files"
        git push
    