name: TestDeply

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build and deploy to GitHub Pages
      run: |
        bundle exec jekyll build -d ${{github.workspace}}/docs
        mv ${{github.workspace}}/docs ${{github.workspace}}/.wiki
      env:
        JEKYLL_ENV: production

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: .wiki